export * from './Home/Home'
export * from './SplashScreen/index'
export * from './Detail/index'
export * from './Login/Login'
export * from './Cadastro/Cadastro'
export * from './Perfil/Profile'
export * from './Contatos/Contatos'
export * from './Partners/Partners'
